"""empty message

Revision ID: c8701f350caf
Revises: aa4b16f7c0b1
Create Date: 2024-03-28 16:31:26.683459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8701f350caf'
down_revision = 'aa4b16f7c0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_leetcode_problems', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('completed_leetcode_problems')

    # ### end Alembic commands ###
